# Generated by Django 3.2.12 on 2022-02-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('induct', '0003_auto_20220226_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='induct_2',
            old_name='destination1',
            new_name='destination_1',
        ),
        migrations.RenameField(
            model_name='induct_2',
            old_name='shipment1',
            new_name='shipment_1',
        ),
    ]
